GET http://localhost:59111/todos/?status=TO%20DO
###

GET http://localhost:59111/todos/?priority=HIGH
###

GET http://localhost:59111/todos/?priority=HIGH&status=IN%20PROGRESS
###

GET http://localhost:59111/todos/?search_q=Play
###

GET http://localhost:59111/todos/2/
###

POST http://localhost:59111/todos/ 
Content-Type:application/json 

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
###

PUT http://localhost:59111/todos/5/
Content-Type:application/json 

{
    "status": "DONE"
}
###

PUT http://localhost:59111/todos/8/ 
Content-Type:application/json 

{
    "priority": "HIGH"
}
###

PUT http://localhost:59111/todos/6/ 
Content-Type:application/json 

{
    "todo": "Some task"
}
###

DELETE http://localhost:59111/todos/7/
###